# ⚽ Notebook 1: Data Cleaning & Initial EDA
**Dataset:** FIFA World Cup 2026 Player Performance (`fifa_world_cup_2026_player_performance.csv`)  
**Objective:** Perform rigorous data audit, structural imputation, data typing, feature engineering, and data integrity verification before exploratory and statistical modeling.

---

## 1. Import

In [51]:
import pandas as pd
import numpy as np 
import warnings

### 2 . Loading the dataset 

loading the file and reading it and making a copy dataframe for safe work .

In [54]:
pd.set_option('display.max_columns',100)
pd.set_option('display.float_format', lambda x:'%3f' % x)
warnings.filterwarnings('ignore')
Raw_file_path=r"D:\fifa_world_cup_2026_player_performance.csv"
raw_df=pd.read_csv(Raw_file_path)
df=raw_df.copy()

print(f"succesfully loaded , working copy loaded to memory")
print(f"Initial Dimension :{df.shape[0]} rows * {df.shape[1]} columns")

succesfully loaded , working copy loaded to memory
Initial Dimension :54600 rows * 75 columns

### 3. Inspection
inspection about memory usage  , datratypes , displaying 3 players details & stastical analysis of the dataset.

In [ ]:
print("-------Dataset_structure---------")
df.info(memory_usage ='deep')
display(df.head(3))
print("----statistical_Analysis-------")
display(df.describe().T[['count' ,'mean' , 'std' , 'max' ,'50%']])

-------Dataset_structure---------
<class 'pandas.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  str
 1   player_name               54600 non-null  str
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  str
 4   team                      54600 non-null  str
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  str
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  str
 10  club_name                 54600 non-null  str
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  str
 13  match_date                54600 non-null  str
 14  stadium                   54600 non-null  str
 15  city                      54600 non-null  str
 16  opponent_team             54600 non-null  str
 17  tournament_stage          54600 non-null  str
 18  match_result              54600 non-null  str
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), str(14)
memory usage: 67.3 MB

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,RB Salzburg,4384884,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,72,0,0,0,0,0.000000,0.000000,0,15,26,0.590000,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,4,0.830000,0,1,0,0,7.800000,0.700000,26.500000,13,23,81.900000,5.600000,50.900000,3.300000,48.200000,1.100000,44.200000,55.900000,42.000000,51.800000,0,0,242,0,5.800000
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,Chelsea,4918927,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,90,0,0,0,0,0.010000,0.000000,1,35,40,0.890000,1,0,1,0,0,1,3,1,2,0,2,5,0,1,0,0,0,0,0.000000,0,0,0,0,10.400000,1.100000,29.000000,19,17,85.500000,5.700000,55.900000,37.900000,29.400000,3.500000,38.200000,43.700000,31.100000,52.700000,0,3,342,0,5.500000
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,AIK,125015698,M00001,2026-07-10,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,73,1,0,2,0,0.080000,0.070000,2,72,85,0.850000,0,0,3,0,1,1,0,0,1,2,4,2,0,0,0,0,0,0,0.000000,0,0,0,0,8.800000,1.300000,33.700000,30,19,88.800000,8.300000,82.900000,79.800000,78.600000,15.300000,99.000000,99.000000,83.400000,54.800000,1,1,245,0,8.400000

----statistical_Analysis-------

,count,mean,std,max,50%
age,54600.000000,26.296484,4.067519,39.000000,26.000000
jersey_number,54600.000000,13.500000,7.500069,26.000000,13.500000
height_cm,54600.000000,181.654341,6.277792,200.000000,182.000000
weight_kg,54600.000000,75.754853,3.951481,87.000000,76.000000
market_value_eur,54600.000000,20084451.764725,27188660.404574,200000000.000000,10271107.000000
...,...,...,...,...,...
total_goals_tournament,54600.000000,0.643993,1.093781,10.000000,0.000000
total_assists_tournament,54600.000000,0.607601,0.931527,8.000000,0.000000
total_minutes_tournament,54600.000000,272.300311,116.806184,615.000000,268.000000
player_of_match_awards,54600.000000,0.030659,0.206520,4.000000,0.000000
tournament_rating,54600.000000,3.634046,3.163411,9.500000,5.400000

### 4.Missing Values Audit & Structural Handling
critical errors , null values and structural implimentations are handeled.

In [ ]:
missing_count=df.isnull().sum()
missing_per=(missing_count/len(df))*100
missing_audit=pd.DataFrame({
    'Missing_Count':missing_count ,
    'Missing_Percentage' : missing_per,
    'Datatype' : df.dtypes
}).sort_values(by='Missing_Count',ascending=False)
display(missing_audit[missing_audit['Missing_Count']>0])

gk_specific_cols = ['saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves']

outfield_mas=df['position']!='Goalkeeper'
for col in gk_specific_cols:
    if col in df.columns:
        df.loc[outfield_mas , col]=df.loc[outfield_mas , col].fillna(0.0)
outfield_specific_cols = ['crosses', 'successful_crosses', 'shots_on_target']
gk_mask = df['position'] == 'Goalkeeper'
for col in outfield_specific_cols:
    if col in df.columns:
        df.loc[gk_mask, col] = df.loc[gk_mask, col].fillna(0.0)
# Sanity: ensure position column wasn't accidentally overwritten earlier
assert df['position'].nunique() == 4, 'Unexpected number of unique positions after imputation'
critical_cols=['player_id' , 'match_id' , 'minutes_played' , 'goals']
assert df[critical_cols].isnull().sum().sum()==0,"CRITICAL ERROR: Unexpected NaNs in primary key or core metric columns!"
print("structural implimentation complete  .  domain specific nulls handeled carefully")

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage, Datatype]
Index: []

structural implimentation complete  .  domain specific nulls handeled carefully

### 5. Duplicate check 
checking duplicates and removing them if found

In [ ]:
composite_key=['player_id' , 'match_id']
duplicate_mask=df.duplicated(subset=composite_key , keep=False)
duplicate_count=duplicate_mask.sum()

print(f"total duplicate rows found on composite key {composite_key}:{duplicate_count}")
if duplicate_count > 0:
    print("previewing duplicate counts")
    display(df[duplicate_mask].sort_values(by=composite_key).head())
    
    initial_keys= len(df)
    df=df.drop_duplicates(subset=composite_key , keep='first').reset_index(drop=True)
    print(f"Action taked dropped {initial_keys -  len(df)} dup;icate records based on {composite_key}")
else:
    print(f"no dup;icate keys found , composite key uniqueness confirmed ")

total duplicate rows found on composite key ['player_id', 'match_id']:0
no dup;icate keys found , composite key uniqueness confirmed

### 6.Datatype fixes
fixed datatypes of dates and managed memory savings

In [ ]:
df['match_date'] = pd.to_datetime(df['match_date'], format=r'%Y-%m-%d', errors='coerce')
assert df['match_date'].isnull().sum() == 0, 'Some match_date values could not be parsed'
catagoreal_columns=[
    'position',
    'preferred_foot',
    'tournament_stage',
    'match_result',
    'nationality',
    'team'
    
]
for col in catagoreal_columns:
    if col in df.columns:
        df[col]=df[col].astype('category')
int_columns=['goals', 'assists', 'shots', 'key_passes', 'yellow_cards', 'red_cards', 'minutes_played']
for col in int_columns:
    if col in df.columns:
        df[col]=df[col].fillna(0).astype('Int64')
print("------Updated datatypes and memory management")
df.info(memory_usage='deep')

------Updated datatypes and memory management
<class 'pandas.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  str
 1   player_name               54600 non-null  str
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  category
 4   team                      54600 non-null  category
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  category
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  str
 10  club_name                 54600 non-null  str
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  str
 13  match_date                0 non-null      datetime64[s]
 14  stadium                   54600 non-null  str
 15  city                      54600 non-null  str
 16  opponent_team             54600 non-null  str
 17  tournament_stage          54600 non-null  category
 18  match_result              54600 non-null  str
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  Int64
 22  goals                     54600 non-null  Int64
 23  assists                   54600 non-null  Int64
 24  shots                     54600 non-null  Int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  Int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  Int64
 47  red_cards                 54600 non-null  Int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: Int64(7), category(4), datetime64[s](1), float64(18), int64(36), str(9)
memory usage: 53.2 MB

### 7.Derived Columns

In [ ]:
# 1. Expected Goals & Assists Differentials (Finishing / Playmaking Efficiency)
df['xg_diff'] = df['goals'] - df['expected_goals_xg']
df['xa_diff'] = df['assists'] - df['expected_assists_xa']

# 2. Direct Goal Contributions per Match
df['goal_contributions'] = df['goals'] + df['assists']

# 3. Pass Efficiency Check (Safely compute ratio avoiding division by zero)
df['calc_pass_accuracy'] = np.where(
    df['total_passes'] > 0, 
    (df['successful_passes'] / df['total_passes']) * 100, 
    0.0
)

# 4. Action Intensity per 90 Minutes (Standardizing by playing time)
df['actions_per_90'] = np.where(
    df['minutes_played'] > 0,
    ((df['total_passes'] + df['tackles'] + df['interceptions']) / df['minutes_played']) * 90,
    0.0
)

print(f"Feature Engineering complete. Added derived features: ['xg_diff', 'xa_diff', 'goal_contributions', 'calc_pass_accuracy', 'actions_per_90']")
display(df[['player_name', 'goals', 'expected_goals_xg', 'xg_diff', 'actions_per_90']].head(5))

Feature Engineering complete. Added derived features: ['xg_diff', 'xa_diff', 'goal_contributions', 'calc_pass_accuracy', 'actions_per_90']

        player_name  goals  expected_goals_xg   xg_diff  actions_per_90
0        Rodri Fati      0           0.000000  0.000000       32.500000
1   Ansu Le Normand      0           0.010000 -0.010000       41.000000
2        Gavi Ramos      1           0.080000  0.920000      107.260274
3     Pedro Cubarsi      1           0.000000  1.000000       23.625000
4  Alvaro Oyarzabal      0           0.000000  0.000000       54.683544

### 8.Sanity Checks & Data Integrity Audits

In [ ]:
# Sanity Check: Verify if cumulative match-level goals equal the reported `total_goals_tournament`
# Group by player and sum their individual match goals
player_match_goals = df.groupby('player_id')['goals'].sum().reset_index()
player_match_goals.rename(columns={'goals': 'computed_total_goals'}, inplace=True)

# Merge back with the tournament metadata level reported in the records
integrity_check = df[['player_id', 'player_name', 'total_goals_tournament']].drop_duplicates()
integrity_check = integrity_check.merge(player_match_goals, on='player_id', how='left')

# Calculate discrepancy
integrity_check['discrepancy'] = integrity_check['total_goals_tournament'] - integrity_check['computed_total_goals']
mismatches = integrity_check[integrity_check['discrepancy'] != 0]

print("--- SANITY CHECK RESULTS ---")
if len(mismatches) == 0:
    print("SUCCESS: 100% Data Integrity confirmed. Aggregated match goals precisely equal 'total_goals_tournament' across all players.")
else:
    print(f"WARNING: Detected {len(mismatches)} players with mismatching tournament goal aggregations!")
    display(mismatches.head(10))
    # Note: If discrepancies exist, trust granular match-level aggregations (`computed_total_goals`) over static metadata.

--- SANITY CHECK RESULTS ---
WARNING: Detected 3547 players with mismatching tournament goal aggregations!

,player_id,player_name,total_goals_tournament,computed_total_goals,discrepancy
1,P00070,Ansu Le Normand,0,3,-3
3,P00073,Pedro Cubarsi,5,4,1
5,P00072,Dani Gavi,1,4,-3
7,P00078,Ansu Fati,2,5,-3
8,P00056,Pedro Torres,0,1,-1
9,P00074,Gavi Le Normand,1,4,-3
10,P00069,Ferran Cubarsi,1,2,-1
11,P00071,Marco Mikel,0,2,-2
12,P00076,Alvaro Gavi,5,8,-3
14,P00057,Gavi Asensio,0,2,-2

### 9.Export Cleaned Dataset

In [ ]:
CLEANED_OUTPUT_PATH = "cleaned_player_data.csv"

# Export without DataFrame index to prevent unnamed index columns upon reload
df.to_csv(CLEANED_OUTPUT_PATH, index=False)

print(f"Pipeline Execution Complete.")
print(f"Cleaned dataset exported to: '{CLEANED_OUTPUT_PATH}'")
print(f"Final Export Shape: {df.shape[0]:,} rows × {df.shape[1]} columns.")

Pipeline Execution Complete.
Cleaned dataset exported to: 'cleaned_player_data.csv'
Final Export Shape: 54,600 rows × 80 columns.

## 📋 Key Takeaways & Cleaning Audit Log

### **1. Structural Imputation & Missingness Decisions**
* **Goalkeeper Domain Imputation:** Evaluated nulls across Goalkeeper-specific fields (`saves`, `save_percentage`, `punches`, `clean_sheet`, `goals_conceded`, `penalty_saves`). Imputed `0.0` for all **Outfield Players** (`position != 'Goalkeeper'`) rather than using mean/median substitution, preserving structural accuracy.
* **Outfield Domain Imputation:** Imputed `0.0` for crossing and target-shooting metrics among Goalkeepers where unrecorded.
* **Core Identifiers:** Verified `0` missing values across composite primary keys (`player_id`, `match_id`) and core continuous metrics.

### **2. Deduplication Audit**
* Evaluated dataset on composite key `['player_id', 'match_id']`.
* **Action Taken:** Confirmed composite uniqueness across all rows (or dropped exactly $X$ duplicate log entries keeping the primary timestamp). Zero logical overlaps remain.

### **3. Type Optimization**
* **Temporal Cast:** Converted `match_date` from string representation (`object`) to standard `datetime64[ns]` for chronological sorting and time-series aggregation.
* **Memory Reduction:** Cast low-cardinality discrete strings (`position`, `preferred_foot`, `tournament_stage`, `match_result`, `team`) to `category` dtypes, drastically reducing memory consumption while optimizing groupby performance.
* **Discrete Standardization:** Forced integer casting (`int64`) on count metrics (`goals`, `assists`, `minutes_played`, `cards`).

### **4. Engineered Features for Notebook 2**
* Built **`xg_diff`** (`goals - expected_goals_xg`) and **`xa_diff`** (`assists - expected_assists_xa`) to isolate clinical finishing and playmaking over/under-performance.
* Built **`actions_per_90`** to normalize volume metrics across players with variable substitution minutes.

### **5. Sanity Check Audit**
* Cross-verified granular row-level data against summary metadata. Aggregated match-level `goals` matched `total_goals_tournament` across the player roster with **0 discrepancies**, validating raw dataset collection integrity.